<!doctype html>
<html lang="en">
  <head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Book Demo | CampusEdgePro</title><meta name="description" content="Book a live demo or explore CampusEdgePro screenshots for college ERP workflows."><link rel="stylesheet" href="/assets/styles.css"></head>
  <body><header class="topbar"><nav class="nav"><a class="brand" href="index.html"><img class="brand-logo" src="/assets/camplogo.png" alt="CampusEdgePro"></a><button class="menu-toggle" data-menu-toggle aria-label="Open menu">ÃƒÂ¢Ã‹Å“Ã‚Â°</button><div class="nav-links" data-nav-links><a href="features.html">Features</a><a href="modules.html">Modules</a><a href="demo.html">Demo</a><a href="pricing.html">Pricing</a><a href="blog.html">Blog</a><a href="about.html">About Us</a><a href="contact.html">Contact</a><a href="docs/index.html">Documentation</a></div><a class="button nav-cta" href="demo.html">Book Demo</a></nav></header>
    <main><section class="section page-hero"><p class="eyebrow">Demo</p><h1>Book a live CampusEdgePro demo.</h1><p class="lead">See student management, attendance, fees, exams, reports and admissions CRM in one guided walkthrough.</p></section>
      <section class="band"><div class="section split demo-section"><section class="demo-video-card card"><div class="demo-video-head"><div><p class="eyebrow">Product walkthrough</p><h2>See the ERP in action.</h2><p>Use this temporary overview preview to showcase the platform before the live guided session.</p></div><span class="demo-live-badge">Overview media</span></div><div class="video-box"><div class="video-box-inner demo-video-media"><img src="/assets/product-overview.gif" alt="CampusEdgePro product overview preview"><span class="video-play-chip">Product overview</span></div></div><div class="demo-video-points"><span>Student management</span><span>Admissions CRM</span><span>Fees and reports</span></div></section><form class="demo-form-card form" action="mailto:hello@sortiqsolutions.com" method="post" enctype="text/plain"><div class="demo-form-head"><div><h3>Book your live demo</h3><p>Share your details and weÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ll tailor the walkthrough to your instituteÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢s workflow.</p></div><span class="demo-live-badge">Live session</span></div><div class="demo-form-body"><label class="field"><span>Name</span><input name="name" required></label><label class="field"><span>Phone</span><input name="phone" required></label><label class="field"><span>Institute</span><input name="institute" required></label><label class="field"><span>Preferred module</span><select name="module"><option>Complete ERP demo</option><option>Admissions CRM</option><option>Fee Management</option><option>Attendance</option></select></label><div class="demo-submit"><button class="button" type="submit">Book Live Demo</button></div></div></form></div></section>
      <section class="section"><div class="section-head"><div><p class="eyebrow">Screenshots</p><h2>Preview the dashboard experience.</h2></div></div><img src="/assets/hero-section-img2.png" alt="CampusEdgePro dashboard screenshot"></section>
    </main><footer class="footer"><div class="footer-inner"><div><a class="brand" href="index.html"><img class="brand-logo" src="/assets/camplogo.png" alt="CampusEdgePro"></a><p>Smart College ERP by Sortiq Solutions.</p></div><div class="footer-links"><div><strong>Website</strong><a href="features.html">Features</a><a href="modules.html">Modules</a><a href="pricing.html">Pricing</a></div><div><strong>Resources</strong><a href="blog.html">Blog</a><a href="docs/index.html">Documentation</a><a href="ads.html">Landing Page</a></div><div><strong>Modules</strong><a href="modules/student-management.html">Students</a><a href="modules/fees.html">Fees</a><a href="modules/attendance.html">Attendance</a></div><div><strong>Contact</strong><a href="contact.html">Book Demo</a><a href="mailto:hello@sortiqsolutions.com">Email</a></div></div></div></footer><script src="/assets/main.js"></script></body>
</html>

