<dialog class="portal-modal" id="{{ $dialogId }}"><div class="portal-modal-body"><div class="portal-card-head"><div><h2>{{ $student ? 'Edit student' : 'Add student' }}</h2></div><button class="portal-button-ghost" onclick="this.closest('dialog').close()">Close</button></div><form class="portal-form-grid" method="post" action="{{ $action }}">@csrf @if($method !== 'post') @method($method) @endif
  <label class="portal-field"><span>Name</span><input name="name" value="{{ old('name', $student?->user?->name) }}" required></label><label class="portal-field"><span>Email</span><input type="email" name="email" value="{{ old('email', $student?->user?->email) }}" required></label>
  <label class="portal-field"><span>Phone</span><input name="phone" value="{{ old('phone', $student?->user?->phone) }}"></label><label class="portal-field"><span>Password</span><input type="password" name="password" {{ $student ? '' : 'required' }}></label>
  <label class="portal-field"><span>Campus</span><select name="campus_id" required>@foreach($campuses as $campus)<option value="{{ $campus->id }}" @selected(old('campus_id', $student?->campus_id) == $campus->id)>{{ $campus->name }}</option>@endforeach</select></label>
  <label class="portal-field"><span>Department</span><select name="department_id" required>@foreach($departments as $department)<option value="{{ $department->id }}" @selected(old('department_id', $student?->department_id) == $department->id)>{{ $department->name }}</option>@endforeach</select></label>
  <label class="portal-field"><span>Course</span><select name="course_id" required>@foreach($courses as $course)<option value="{{ $course->id }}" @selected(old('course_id', $student?->course_id) == $course->id)>{{ $course->name }}</option>@endforeach</select></label>
  <label class="portal-field"><span>Roll number</span><input name="roll_number" value="{{ old('roll_number', $student?->roll_number) }}" required></label><label class="portal-field"><span>Registration number</span><input name="registration_number" value="{{ old('registration_number', $student?->registration_number) }}" required></label>
  <label class="portal-field"><span>DOB</span><input type="date" name="dob" value="{{ old('dob', $student?->dob?->format('Y-m-d')) }}"></label><label class="portal-field"><span>Gender</span><input name="gender" value="{{ old('gender', $student?->gender) }}"></label>
  <label class="portal-field"><span>Guardian name</span><input name="guardian_name" value="{{ old('guardian_name', $student?->guardian_name) }}"></label><label class="portal-field"><span>Guardian phone</span><input name="guardian_phone" value="{{ old('guardian_phone', $student?->guardian_phone) }}"></label>
  <label class="portal-field"><span>Admission date</span><input type="date" name="admission_date" value="{{ old('admission_date', $student?->admission_date?->format('Y-m-d') ?? now()->toDateString()) }}" required></label><label class="portal-field"><span>Status</span><select name="status"><option value="active" @selected(old('status', $student?->status ?? 'active') === 'active')>Active</option><option value="inactive" @selected(old('status', $student?->status) === 'inactive')>Inactive</option><option value="graduated" @selected(old('status', $student?->status) === 'graduated')>Graduated</option><option value="suspended" @selected(old('status', $student?->status) === 'suspended')>Suspended</option></select></label>
  <label class="portal-field full"><span>Address</span><textarea name="address">{{ old('address', $student?->address) }}</textarea></label><div class="full"><button class="portal-button">Save student</button></div>
</form></div></dialog>
